$font = JetBrains Mono Nerd Font
$font_size = 40

# hides cursor on locked screen
general {
			hide_cursor = true
}

# lockscreen wallpaper
background {
			monitor =
			path = $HOME/.config/hypr/backgrounds/alena-aenami-any-minute-now.jpg
			color = #ffffff
			blur_passes = 1
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $text
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# password field
input-field {
			monitor = 
			size = 200, 50
			outline_thickness = 3
			rounding = 10
			dots_size = 0.1
			dots_spacing = 0.1
			dots_center = true
			outer_color = #rgb(255, 255, 255)
			inner_color = rgb(0, 0, 0)
			font_color = rgb(255, 255, 255)
			fade_on_empty = false
			placeholder_text =
			hide_input = false
			check_color = #565f89
			position = 0, -500
			halign = center
			valign = center
}
